version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5673:5672" 
      - "15673:15672" 

    networks:
      - app-network

  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
