version: '3'
services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq_pubsub"
    ports:
      - "5672:5672"
      - "15672:15672"  # Interface Web RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
